// Map sprite registry for the tram model "faces" — the PNG rasterizations of
// the vector faces in src/components/tram/faces/*, generated by
// scripts/tram-models/render-face-sprites.mjs (same art, rendered at
// FACE_SPRITE_SCALE× raw pixels on a transparent background).
//
// For SymbolLayer use: register each asset with scale=FACE_SPRITE_SCALE so
// iconSize works in sensible pt units — same pattern as MAP_ICON_ASSETS /
// MAP_ICON_SCALE in './modelSpecs'.

import type { TramModelId } from '@/lib/types';

/**
 * Wrap the metro asset require so the module also loads under jest, where the
 * PNG may not be in the transformer allowlist (metro resolves these statically
 * at bundle time, so a missing file still fails the app build).
 */
function pngAsset(load: () => number): number {
  try {
    return load();
  } catch {
    return 0;
  }
}

/** Face sprites are rendered at 3× raw pixels (192 px for a 64 pt face). */
export const FACE_SPRITE_SCALE = 3;

/** modelId → bundled face-sprite PNG asset id. */
export const FACE_SPRITE_ASSETS: Record<TramModelId, number> = {
  t3: pngAsset(() => require('../../../assets/images/faces/t3.png')),
  t3rp: pngAsset(() => require('../../../assets/images/faces/t3rp.png')),
  t3rplf: pngAsset(() => require('../../../assets/images/faces/t3rplf.png')),
  kt8d5: pngAsset(() => require('../../../assets/images/faces/kt8d5.png')),
  '14t': pngAsset(() => require('../../../assets/images/faces/14t.png')),
  '15t': pngAsset(() => require('../../../assets/images/faces/15t.png')),
  '52t': pngAsset(() => require('../../../assets/images/faces/52t.png')),
};
