// Icon-pack registry — the single source of truth for the tram "face" art.
// Each pack is a complete set of 7 model faces in one distinct style
// (src/components/tram/faces/packs/<packId>/) plus the matching baked map
// sprites (assets/images/faces/<packId>/<modelId>.png, generated by
// scripts/tram-models/render-face-sprites.mjs from the SAME vector art).
//
// Consumers:
//  - TramFace renders ICON_PACKS[pack].faces[modelId] (pack defaults to the
//    user's settings-store selection).
//  - TramLayers registers every pack's sprites as 'face-<pack>-<modelId>' and
//    picks the selected pack's sprite via a style expression.
//  - settings.tsx builds the pack picker from ICON_PACK_IDS + meta.

import type React from 'react';

import type { TramModelId } from '@/lib/types';

import {
  FACES as chibiFaces,
  PACK_META as chibiMeta,
} from '@/components/tram/faces/packs/chibi';
import {
  FACES as classicFaces,
  PACK_META as classicMeta,
} from '@/components/tram/faces/packs/classic';
import { FACES as isoFaces, PACK_META as isoMeta } from '@/components/tram/faces/packs/iso';
import { FACES as sideFaces, PACK_META as sideMeta } from '@/components/tram/faces/packs/side';

export type IconPackId = 'classic' | 'side' | 'iso' | 'chibi';

/** All packs, in picker order (classic — the default — first). */
export const ICON_PACK_IDS: IconPackId[] = ['classic', 'side', 'iso', 'chibi'];

export const DEFAULT_ICON_PACK: IconPackId = 'classic';

/** Face sprites are rendered at 3× raw pixels (192 px for a 64 pt face). */
export const FACE_SPRITE_SCALE = 3;

/**
 * Wrap the metro asset require so the module also loads under jest, where the
 * PNG may not be in the transformer allowlist (metro resolves these statically
 * at bundle time, so a missing file still fails the app build).
 */
function pngAsset(load: () => number): number {
  try {
    return load();
  } catch {
    return 0;
  }
}

export interface IconPack {
  meta: { id: IconPackId; name: string; description: string };
  faces: Record<TramModelId, React.FC<{ size?: number }>>;
  /** modelId → bundled face-sprite PNG asset id (for the map badge layers). */
  sprites: Record<TramModelId, number>;
}

export const ICON_PACKS: Record<IconPackId, IconPack> = {
  classic: {
    meta: classicMeta,
    faces: classicFaces,
    sprites: {
      t3: pngAsset(() => require('../../../assets/images/faces/classic/t3.png')),
      t3rp: pngAsset(() => require('../../../assets/images/faces/classic/t3rp.png')),
      t3rplf: pngAsset(() => require('../../../assets/images/faces/classic/t3rplf.png')),
      kt8d5: pngAsset(() => require('../../../assets/images/faces/classic/kt8d5.png')),
      '14t': pngAsset(() => require('../../../assets/images/faces/classic/14t.png')),
      '15t': pngAsset(() => require('../../../assets/images/faces/classic/15t.png')),
      '52t': pngAsset(() => require('../../../assets/images/faces/classic/52t.png')),
    },
  },
  side: {
    meta: sideMeta,
    faces: sideFaces,
    sprites: {
      t3: pngAsset(() => require('../../../assets/images/faces/side/t3.png')),
      t3rp: pngAsset(() => require('../../../assets/images/faces/side/t3rp.png')),
      t3rplf: pngAsset(() => require('../../../assets/images/faces/side/t3rplf.png')),
      kt8d5: pngAsset(() => require('../../../assets/images/faces/side/kt8d5.png')),
      '14t': pngAsset(() => require('../../../assets/images/faces/side/14t.png')),
      '15t': pngAsset(() => require('../../../assets/images/faces/side/15t.png')),
      '52t': pngAsset(() => require('../../../assets/images/faces/side/52t.png')),
    },
  },
  iso: {
    meta: isoMeta,
    faces: isoFaces,
    sprites: {
      t3: pngAsset(() => require('../../../assets/images/faces/iso/t3.png')),
      t3rp: pngAsset(() => require('../../../assets/images/faces/iso/t3rp.png')),
      t3rplf: pngAsset(() => require('../../../assets/images/faces/iso/t3rplf.png')),
      kt8d5: pngAsset(() => require('../../../assets/images/faces/iso/kt8d5.png')),
      '14t': pngAsset(() => require('../../../assets/images/faces/iso/14t.png')),
      '15t': pngAsset(() => require('../../../assets/images/faces/iso/15t.png')),
      '52t': pngAsset(() => require('../../../assets/images/faces/iso/52t.png')),
    },
  },
  chibi: {
    meta: chibiMeta,
    faces: chibiFaces,
    sprites: {
      t3: pngAsset(() => require('../../../assets/images/faces/chibi/t3.png')),
      t3rp: pngAsset(() => require('../../../assets/images/faces/chibi/t3rp.png')),
      t3rplf: pngAsset(() => require('../../../assets/images/faces/chibi/t3rplf.png')),
      kt8d5: pngAsset(() => require('../../../assets/images/faces/chibi/kt8d5.png')),
      '14t': pngAsset(() => require('../../../assets/images/faces/chibi/14t.png')),
      '15t': pngAsset(() => require('../../../assets/images/faces/chibi/15t.png')),
      '52t': pngAsset(() => require('../../../assets/images/faces/chibi/52t.png')),
    },
  },
};

/**
 * Face component for a pack + model, with defensive fallback: an unknown pack
 * falls back to the default pack, an unknown model to the classic T3.
 */
export function getFace(
  pack: IconPackId,
  modelId: TramModelId,
): React.FC<{ size?: number }> {
  const packEntry = ICON_PACKS[pack] ?? ICON_PACKS[DEFAULT_ICON_PACK];
  return packEntry.faces[modelId] ?? ICON_PACKS[DEFAULT_ICON_PACK].faces.t3;
}
