// Tram model specs + GLB asset registry. Dimensions from
// docs/research/prague-fleet.md (DPP official spec sheets, snapshot 2026-07).
// sections[].modelKey values match assets/models/<key>.glb exactly — the GLBs
// are generated by scripts/generate-tram-models.mjs.
//
// sections[].openModelKey ('<modelKey>-open') is the doors-OPEN GLB variant
// (right-side passenger doors slid aside, warm interior glow) rendered while a
// tram dwells at a stop. Sections without passenger doors (14t-a driver-door
// cab, 52t-b/d pantograph middles) have no open variant.

import type { TramModelId, TramModelSpec } from '@/lib/types';

export const MODEL_SPECS: Record<TramModelId, TramModelSpec> = {
  t3: {
    id: 't3',
    name: 'Tatra T3',
    manufacturer: 'ČKD Tatra',
    yearsBuilt: '1960–1976',
    sections: [{ modelKey: 't3', openModelKey: 't3-open', lengthM: 14.1 }],
    jointGapM: 0,
    totalLengthM: 14.1,
    widthM: 2.5,
    heightM: 3.06,
    maxSpeedKmh: 65,
    lowFloor: false,
    runsCoupled: true,
    funFact:
      'The Tatra T3 is the most-produced tram design in history — nearly 14,000 were built, and Prague alone once ran over 1,000 of them.',
  },
  t3rp: {
    id: 't3rp',
    name: 'Tatra T3R.P',
    manufacturer: 'ČKD Tatra / Pars Nova (rebuild)',
    yearsBuilt: '1963–1973, rebuilt 2000s',
    sections: [{ modelKey: 't3rp', openModelKey: 't3rp-open', lengthM: 14.1 }],
    jointGapM: 0,
    totalLengthM: 14.1,
    widthM: 2.5,
    heightM: 3.06,
    maxSpeedKmh: 65,
    lowFloor: false,
    runsCoupled: true,
    funFact:
      'T3R.P cars are 1960s T3 shells reborn with modern electronics — they usually roam Prague in coupled two-car pairs.',
  },
  t3rplf: {
    id: 't3rplf',
    name: 'Tatra T3R.PLF',
    manufacturer: 'ČKD Tatra / DPP–KOS Krnov (rebuild)',
    yearsBuilt: 'rebuilt 2007–present',
    sections: [{ modelKey: 't3rplf', openModelKey: 't3rplf-open', lengthM: 14.1 }],
    jointGapM: 0,
    totalLengthM: 14.1,
    widthM: 2.48,
    heightM: 3.19,
    maxSpeedKmh: 65,
    lowFloor: true,
    runsCoupled: true,
    funFact:
      'The PLF hides a low-floor "bathtub" middle inside the classic T3 shell — enthusiasts nicknamed the stepped floor section "vana".',
  },
  kt8d5: {
    id: 'kt8d5',
    name: 'Tatra KT8D5.RN2P',
    manufacturer: 'ČKD Tatra / KOS Krnov (rebuild)',
    yearsBuilt: '1986–1990, rebuilt 2014–present',
    sections: [
      { modelKey: 'kt8d5-a', openModelKey: 'kt8d5-a-open', lengthM: 10.0 },
      { modelKey: 'kt8d5-b', openModelKey: 'kt8d5-b-open', lengthM: 9.7 },
      { modelKey: 'kt8d5-c', openModelKey: 'kt8d5-c-open', lengthM: 10.0 },
    ],
    jointGapM: 0.3,
    totalLengthM: 30.3,
    widthM: 2.48,
    heightM: 3.15,
    maxSpeedKmh: 65,
    lowFloor: true,
    runsCoupled: false,
    funFact:
      'Many Prague KT8D5s are immigrants — retired trams bought back from Miskolc in Hungary and rebuilt with a new low-floor middle section.',
  },
  '14t': {
    id: '14t',
    name: 'Škoda 14T Elektra',
    manufacturer: 'Škoda Transportation',
    yearsBuilt: '2006–2010',
    sections: [
      { modelKey: '14t-a', lengthM: 6.95 },
      { modelKey: '14t-b', openModelKey: '14t-b-open', lengthM: 4.35 },
      { modelKey: '14t-c', openModelKey: '14t-c-open', lengthM: 6.95 },
      { modelKey: '14t-d', openModelKey: '14t-d-open', lengthM: 4.35 },
      { modelKey: '14t-e', openModelKey: '14t-e-open', lengthM: 6.95 },
    ],
    jointGapM: 0.175,
    totalLengthM: 30.25,
    widthM: 2.46,
    heightM: 3.37,
    maxSpeedKmh: 60,
    lowFloor: true,
    runsCoupled: false,
    funFact:
      'The wedge-nosed 14T was styled by Porsche Design Studio — Praguers promptly nicknamed the noisy five-section tram "Blues".',
  },
  '15t': {
    id: '15t',
    name: 'Škoda 15T ForCity Alfa',
    manufacturer: 'Škoda Transportation',
    yearsBuilt: '2009–2017',
    sections: [
      { modelKey: '15t-a', openModelKey: '15t-a-open', lengthM: 10.3 },
      { modelKey: '15t-b', openModelKey: '15t-b-open', lengthM: 10.3 },
      { modelKey: '15t-c', openModelKey: '15t-c-open', lengthM: 10.3 },
    ],
    jointGapM: 0.25,
    totalLengthM: 31.4,
    widthM: 2.46,
    heightM: 3.45,
    maxSpeedKmh: 60,
    lowFloor: true,
    runsCoupled: false,
    funFact:
      'With 250 cars, the 100% low-floor 15T is the backbone of the Prague fleet — every one of its 16 wheels is individually driven.',
  },
  '52t': {
    id: '52t',
    name: 'Škoda 52T ForCity Plus',
    manufacturer: 'Škoda Transportation',
    yearsBuilt: '2025–present',
    sections: [
      { modelKey: '52t-a', openModelKey: '52t-a-open', lengthM: 6.9 },
      { modelKey: '52t-b', lengthM: 5.8 },
      { modelKey: '52t-c', openModelKey: '52t-c-open', lengthM: 5.6 },
      { modelKey: '52t-d', lengthM: 5.8 },
      { modelKey: '52t-e', openModelKey: '52t-e-open', lengthM: 6.9 },
    ],
    jointGapM: 0.25,
    totalLengthM: 32.0,
    widthM: 2.5,
    heightM: 3.35,
    maxSpeedKmh: 70,
    lowFloor: true,
    runsCoupled: false,
    funFact:
      'Prague’s newest tram watches the street with LiDAR anti-collision sensors and wears the first factory-applied grey-and-red PID livery.',
  },
};

/**
 * Wrap the metro asset require so the module also loads under jest, where
 * `.glb` is not in the transformer allowlist (metro resolves these statically
 * at bundle time, so a missing file still fails the app build).
 */
function glbAsset(load: () => number): number {
  try {
    return load();
  } catch {
    return 0;
  }
}

/** modelKey → bundled GLB asset id, for `Asset.fromModule` + <Models>. */
export const MODEL_ASSETS: Record<string, number> = {
  t3: glbAsset(() => require('../../../assets/models/t3.glb')),
  t3rp: glbAsset(() => require('../../../assets/models/t3rp.glb')),
  t3rplf: glbAsset(() => require('../../../assets/models/t3rplf.glb')),
  'kt8d5-a': glbAsset(() => require('../../../assets/models/kt8d5-a.glb')),
  'kt8d5-b': glbAsset(() => require('../../../assets/models/kt8d5-b.glb')),
  'kt8d5-c': glbAsset(() => require('../../../assets/models/kt8d5-c.glb')),
  '14t-a': glbAsset(() => require('../../../assets/models/14t-a.glb')),
  '14t-b': glbAsset(() => require('../../../assets/models/14t-b.glb')),
  '14t-c': glbAsset(() => require('../../../assets/models/14t-c.glb')),
  '14t-d': glbAsset(() => require('../../../assets/models/14t-d.glb')),
  '14t-e': glbAsset(() => require('../../../assets/models/14t-e.glb')),
  '15t-a': glbAsset(() => require('../../../assets/models/15t-a.glb')),
  '15t-b': glbAsset(() => require('../../../assets/models/15t-b.glb')),
  '15t-c': glbAsset(() => require('../../../assets/models/15t-c.glb')),
  '52t-a': glbAsset(() => require('../../../assets/models/52t-a.glb')),
  '52t-b': glbAsset(() => require('../../../assets/models/52t-b.glb')),
  '52t-c': glbAsset(() => require('../../../assets/models/52t-c.glb')),
  '52t-d': glbAsset(() => require('../../../assets/models/52t-d.glb')),
  '52t-e': glbAsset(() => require('../../../assets/models/52t-e.glb')),
  // doors-OPEN variants (sections[].openModelKey), shown while dwelling
  't3-open': glbAsset(() => require('../../../assets/models/t3-open.glb')),
  't3rp-open': glbAsset(() => require('../../../assets/models/t3rp-open.glb')),
  't3rplf-open': glbAsset(() => require('../../../assets/models/t3rplf-open.glb')),
  'kt8d5-a-open': glbAsset(() => require('../../../assets/models/kt8d5-a-open.glb')),
  'kt8d5-b-open': glbAsset(() => require('../../../assets/models/kt8d5-b-open.glb')),
  'kt8d5-c-open': glbAsset(() => require('../../../assets/models/kt8d5-c-open.glb')),
  '14t-b-open': glbAsset(() => require('../../../assets/models/14t-b-open.glb')),
  '14t-c-open': glbAsset(() => require('../../../assets/models/14t-c-open.glb')),
  '14t-d-open': glbAsset(() => require('../../../assets/models/14t-d-open.glb')),
  '14t-e-open': glbAsset(() => require('../../../assets/models/14t-e-open.glb')),
  '15t-a-open': glbAsset(() => require('../../../assets/models/15t-a-open.glb')),
  '15t-b-open': glbAsset(() => require('../../../assets/models/15t-b-open.glb')),
  '15t-c-open': glbAsset(() => require('../../../assets/models/15t-c-open.glb')),
  '52t-a-open': glbAsset(() => require('../../../assets/models/52t-a-open.glb')),
  '52t-c-open': glbAsset(() => require('../../../assets/models/52t-c-open.glb')),
  '52t-e-open': glbAsset(() => require('../../../assets/models/52t-e-open.glb')),
};

/**
 * Prague tram-stop totem GLB (JŽP-style sign pole), for the map's stop markers.
 * Kept as its own export rather than in MODEL_ASSETS on purpose: the model-specs
 * test asserts MODEL_ASSETS has no keys that a TramModelSpec doesn't reference,
 * and the totem is not a tram. Register it alongside MODEL_ASSETS when loading
 * <Models>, e.g. `{ ...MODEL_ASSETS, 'stop-totem': STOP_TOTEM_ASSET }`.
 */
export const STOP_TOTEM_ASSET: number = glbAsset(
  () => require('../../../assets/models/stop-totem.glb'),
);

/** UI thumbnail (3/4-front, transparent bg) per tram model, for lists/sheets. */
export const MODEL_IMAGES: Record<TramModelId, number> = {
  t3: glbAsset(() => require('../../../assets/images/trams/t3.png')),
  t3rp: glbAsset(() => require('../../../assets/images/trams/t3rp.png')),
  t3rplf: glbAsset(() => require('../../../assets/images/trams/t3rplf.png')),
  kt8d5: glbAsset(() => require('../../../assets/images/trams/kt8d5.png')),
  '14t': glbAsset(() => require('../../../assets/images/trams/14t.png')),
  '15t': glbAsset(() => require('../../../assets/images/trams/15t.png')),
  '52t': glbAsset(() => require('../../../assets/images/trams/52t.png')),
};
