// Live fleet rendering: two ShapeSources fed imperatively per engine frame
// (no React state per frame), zoom-banded layers per architecture.md:
//   <13.2 direction teardrops (bearing-rotated SymbolLayer) ·
//   13.2–14.8 model capsule badges (side silhouette + line number) with a
//   map-aligned heading pointer · ≥14.8 3D ModelLayer,
// plus transparent hit-test circles on BOTH sources (tap anywhere on a tram
// body) and a gold selection halo.
//
// Sprites (19 fixed PNGs, generated by scripts/tram-models/render-map-icons.mjs)
// are loaded through expo-asset localUri — same Fabric-safe pattern as the
// GLBs — and registered via <Images>. All icon variants are picked by style
// EXPRESSIONS over props the points FC already carried (line/modelId/bearing/
// favorite), so the 60 Hz push payload did not grow.
//
// Cadence (zoom-adaptive, thermal-aware): the engine ticks at TICK_MS (~16 ms)
// while the map is in the glide band (zoom ≥ 14, hysteresis down to 13.7 —
// aligned with the fast points cadence so 15 Hz pushes never sample 10 Hz
// motion); at far zooms the runtime drops to ~10 Hz (see
// tramData.setDetailZoom). Each tick pushes the sections
// FC (small — viewport-culled) when the band is on screen; the points FC
// (whole fleet, badges/dots) is pushed at a zoom-dependent cadence
// (pointsPushIntervalMs: 15 Hz close, 1 s mid, 5 s far — far-zoom badges are
// near-static and re-pushing burns GPU). The follow camera is retargeted at
// ~12.5 Hz (CAMERA_RETARGET_MS) with overlapping linear glides, and a
// stationary-target deadband keeps a dwelling tram from restarting native
// camera animations at all — see ./followCamera.ts. Stringify is skipped
// entirely while a FC stays empty, and frames that push nothing skip
// buildFrame altogether.

import {
  Camera,
  CircleLayer,
  Images,
  LineLayer,
  ModelLayer,
  Models,
  ShapeSource,
  SymbolLayer,
} from '@rnmapbox/maps';
import { Asset } from 'expo-asset';
import * as Haptics from 'expo-haptics';
import { router } from 'expo-router';
import {
  useCallback,
  useEffect,
  useRef,
  useState,
  type ReactElement,
  type RefObject,
} from 'react';

import { Tram } from '@/constants/theme';
import { getRuntime, pointsPushIntervalMs } from '@/hooks/tramData';
import { MAP_ICON_ASSETS, MAP_ICON_SCALE } from '@/lib/fleet/modelSpecs';
import { bearingAt, pointAt } from '@/lib/geo/polyline';
import { buildFrame } from '@/lib/render/featureBuilder';
import type { PlannerItinerary, Viewport } from '@/lib/types';
import { useFavoritesStore } from '@/stores/favorites';
import { usePlannerStore } from '@/stores/planner';
import { useSelectionStore } from '@/stores/selection';
import { useSettingsStore } from '@/stores/settings';
import {
  CAMERA_DWELL_EVAL_MS,
  CAMERA_DWELL_SPEED_KMH,
  CAMERA_GLIDE_MS,
  CAMERA_RETARGET_MS,
  leadTarget,
  withinDeadband,
  type FollowCameraTarget,
} from './followCamera';
import {
  BAND_BADGES_TO_MODELS,
  BAND_DOTS_TO_BADGES,
  BAND_FADE,
  SECTIONS_FEED_MIN_ZOOM,
} from './mapStyle';

/**
 * Comic-scale curve: models only reach real-world 1× at this zoom (deeper than
 * the old MODEL_REAL_SCALE_ZOOM=16.6 — mid zooms stay comically oversized).
 */
const MODEL_COMIC_REAL_SCALE_ZOOM = 17.0;

const EMPTY_FC: GeoJSON.FeatureCollection = { type: 'FeatureCollection', features: [] };
const EMPTY_FC_STRING = JSON.stringify(EMPTY_FC);

/**
 * Follow-camera defaults: close chase view from BEHIND the tram, looking
 * forward over the roof (heading = tram bearing) — buildings no longer occlude
 * the followed tram. User gestures during follow adjust zoom/pitch/heading as
 * OFFSETS that persist for the rest of the follow (see FollowGestureState).
 */
const FOLLOW_ZOOM = 17.5;
const FOLLOW_PITCH = 60;

/**
 * Live gesture/override channel between the map screen (which owns
 * onCameraChanged / onMapIdle) and the follow-camera retarget loop here.
 * Gestures do NOT cancel follow — while a gesture is active the retarget loop
 * yields, and the user's chosen zoom/pitch/heading-offset are captured and
 * re-applied relative to the tram bearing on subsequent retargets.
 */
export interface FollowGestureState {
  /** True while the user's fingers are on the map (retargeting pauses). */
  gestureActive: boolean;
  /** Camera overrides captured from the user's gesture; null = defaults. */
  overrides: { zoom: number; pitch: number; headingOffset: number } | null;
}

// Cadence constants, target leading and the stationary-target deadband live
// in ./followCamera (pure module — see the doc comments there).

/** Night lines 90–99 use the navy sprite variants instead of PID red. */
const NIGHT_LINE = ['>=', ['to-number', ['get', 'line']], 90];

/**
 * Direction teardrop sprite: dot-<day|night>[-fav]. Variant is derived from
 * props the points FC already carries — no extra payload on pushes.
 * (Casts follow the file's ModelLayer precedent — rnmapbox's Value<> types
 * don't model nested expressions.)
 */
const DOT_ICON = [
  'concat',
  'dot-',
  ['case', NIGHT_LINE, 'night', 'day'],
  ['case', ['==', ['get', 'favorite'], 1], '-fav', ''],
] as unknown as string;

/** Capsule badge sprite: cap-<modelId>-<day|night> (side silhouette baked in). */
const CAP_ICON = [
  'concat',
  'cap-',
  ['get', 'modelId'],
  ['case', NIGHT_LINE, '-night', '-day'],
] as unknown as string;

/**
 * Line-number seat inside the capsule sprite sits 23 pt left of the sprite
 * center (at iconSize 1); the capsule itself floats above the marker
 * (iconAnchor bottom + 14 pt gap → seat center is 14+10=24 pt above the
 * point). textSize interpolates in lockstep with iconSize, so constant em
 * offsets keep the number seated across the whole band.
 */
const CAP_TEXT_MAX_SIZE = 14;
const CAP_TEXT_OFFSET_EM = -23 / CAP_TEXT_MAX_SIZE;
const CAP_TEXT_OFFSET_UP_EM = -24 / CAP_TEXT_MAX_SIZE;

/** Shared crossfade for every band-2 (badge) layer. */
const BADGE_BAND_OPACITY = [
  'interpolate',
  ['linear'],
  ['zoom'],
  BAND_DOTS_TO_BADGES - BAND_FADE,
  0,
  BAND_DOTS_TO_BADGES + BAND_FADE,
  1,
  BAND_BADGES_TO_MODELS,
  1,
  BAND_BADGES_TO_MODELS + BAND_FADE,
  0,
] as unknown as number;

/**
 * Map icon sprites resolved through expo-asset (same Fabric-safe localUri
 * pattern as the GLBs — see useTramModels) and registered with a pixel-ratio
 * scale so iconSize works in pt-like units. Null while loading; layers that
 * need the sprites mount only once they're registered.
 */
function useMapIcons(): Record<string, { url: string; scale: number }> | null {
  const [icons, setIcons] = useState<Record<string, { url: string; scale: number }> | null>(
    null,
  );
  useEffect(() => {
    let cancelled = false;
    (async () => {
      const entries = Object.entries(MAP_ICON_ASSETS).filter(([, moduleId]) => !!moduleId);
      const pairs = await Promise.all(
        entries.map(async ([key, moduleId]) => {
          const asset = Asset.fromModule(moduleId);
          await asset.downloadAsync();
          return [key, { url: asset.localUri ?? asset.uri, scale: MAP_ICON_SCALE }] as const;
        }),
      );
      if (!cancelled) setIcons(Object.fromEntries(pairs));
    })().catch((e) => {
      console.warn('[map] map icon sprites failed to load — using fallback dots', e);
    });
    return () => {
      cancelled = true;
    };
  }, []);
  return icons;
}

export interface TramLayersProps {
  cameraRef: RefObject<Camera | null>;
  viewportRef: RefObject<Viewport>;
  /** Gesture/override state for the follow camera (owned by the map screen). */
  followGestureRef: RefObject<FollowGestureState>;
  /** modelKey → local GLB URI; null while still downloading (gates <Models>). */
  modelUris: Record<string, string> | null;
}

export function TramLayers({
  cameraRef,
  viewportRef,
  followGestureRef,
  modelUris,
}: TramLayersProps) {
  const iconImages = useMapIcons();
  const pointsRef = useRef<ShapeSource>(null);
  const sectionsRef = useRef<ShapeSource>(null);
  const fixOverlayRef = useRef<ShapeSource>(null);
  const sectionsFedRef = useRef(false);
  const sectionsEmptyRef = useRef(true);
  const fixEmptyRef = useRef(true);
  const lastPointsPushMsRef = useRef(0);
  /** Next follow-camera evaluation is skipped until this timestamp. */
  const cameraEvalDueMsRef = useRef(0);
  /**
   * The last camera target actually SENT (deadband reference). Null whenever
   * the camera is not authoritatively ours — not following, or the user's
   * fingers are on the map — so the next retarget always fires.
   */
  const lastSentCameraRef = useRef<(FollowCameraTarget & { key: string }) | null>(null);
  const favSetRef = useRef<{ source: string[]; set: Set<string> } | null>(null);
  const lineFilterRef = useRef<{
    source: PlannerItinerary | null;
    set: Set<string> | null;
  }>({ source: null, set: null });

  // Per-frame push: engine states → GeoJSON → setNativeProps. Refs only.
  useEffect(() => {
    const rt = getRuntime();
    const getGeometry = (key: string) => rt.engine.getGeometry(key);

    return rt.subscribeFrame((nowMs) => {
      const viewport = viewportRef.current;
      const selection = useSelectionStore.getState();

      // Cheap getState() read per frame — the toggle lives in a form sheet and
      // changes rarely; no subscription bookkeeping needed.
      const positionMode = useSettingsStore.getState().positionMode;

      // Zoom-adaptive push cadences (thermal): sections every tick but ONLY
      // inside the model band; points at pointsPushIntervalMs(zoom).
      const wantSections = viewport.zoom >= SECTIONS_FEED_MIN_ZOOM;
      const wantPoints =
        nowMs - lastPointsPushMsRef.current >= pointsPushIntervalMs(viewport.zoom);

      // On leaving the band the sections source is cleared once so stale
      // models never linger — no frame build needed for that.
      if (!wantSections && sectionsFedRef.current) {
        sectionsFedRef.current = false;
        sectionsEmptyRef.current = true;
        sectionsRef.current?.setNativeProps({ id: 'trams-sections', shape: EMPTY_FC_STRING });
      }

      if (wantPoints || wantSections) {
        const favTrams = useFavoritesStore.getState().favoriteTrams;
        if (!favSetRef.current || favSetRef.current.source !== favTrams) {
          favSetRef.current = { source: favTrams, set: new Set(favTrams) };
        }

        // Planner route-only mode: while an itinerary is shown, only trams on
        // its legs' lines render. The line set is cached per itinerary ref.
        const itinerary = usePlannerStore.getState().itinerary;
        if (lineFilterRef.current.source !== itinerary) {
          lineFilterRef.current = {
            source: itinerary,
            set: itinerary ? new Set(itinerary.legs.map((leg) => leg.line)) : null,
          };
        }

        const frame = buildFrame(rt.engine.getStates(nowMs), viewport, {
          selectedKey: selection.selectedTramKey,
          favoriteKeys: favSetRef.current.set,
          coupledPairFn: rt.coupledPairFn,
          getGeometry,
          lineFilter: lineFilterRef.current.set,
          skipPoints: !wantPoints,
          positionMode,
          nowMs,
        });

        if (wantPoints) {
          lastPointsPushMsRef.current = nowMs;
          pointsRef.current?.setNativeProps({
            id: 'trams-points',
            shape: JSON.stringify(frame.points),
          });
        }

        // While the FC stays empty (no visible trams) the stringify+push is
        // skipped.
        if (wantSections) {
          const isEmpty = frame.sections.features.length === 0;
          if (!isEmpty || !sectionsEmptyRef.current) {
            sectionsRef.current?.setNativeProps({
              id: 'trams-sections',
              shape: isEmpty ? EMPTY_FC_STRING : JSON.stringify(frame.sections),
            });
          }
          sectionsEmptyRef.current = isEmpty;
          sectionsFedRef.current = true;
        }

        // Last-real-fix overlay for the selected/followed tram (dashed
        // connector + fix dot). Pushed at the sections cadence; defensive
        // `??` until the featureBuilder workstream populates fixOverlay.
        const fixFC = (frame.fixOverlay ?? EMPTY_FC) as GeoJSON.FeatureCollection;
        const fixEmpty = fixFC.features.length === 0;
        if (!fixEmpty || !fixEmptyRef.current) {
          fixOverlayRef.current?.setNativeProps({
            id: 'tram-fix-overlay',
            shape: fixEmpty ? EMPTY_FC_STRING : JSON.stringify(fixFC),
          });
        }
        fixEmptyRef.current = fixEmpty;
      }

      // Follow camera: runs ONLY while following. Retarget every
      // CAMERA_RETARGET_MS (NOT every tick — see followCamera.ts) with a
      // longer overlapping glide; targets inside the stationary deadband are
      // not re-sent at all, so a tram dwelling at a stop lets the native map
      // go fully idle. Engine state is read fresh at each retarget. While the
      // user's fingers are on the map the loop yields (gestures adjust the
      // view WITHOUT cancelling follow); their captured zoom/pitch/heading-
      // offset then override the defaults.
      const followKey = selection.followTramKey;
      if (!followKey) {
        lastSentCameraRef.current = null;
        return;
      }
      const gesture = followGestureRef.current;
      if (gesture?.gestureActive) {
        // The user owns the camera while touching. Forget the last-sent
        // target and re-arm the eval clock so the first retarget after
        // release fires immediately — the deadband must never leave the
        // camera wherever a pan ended just because the tram itself is parked.
        lastSentCameraRef.current = null;
        cameraEvalDueMsRef.current = 0;
        return;
      }
      const lastSent = lastSentCameraRef.current;
      // A target switch (follow started / spotter hop to another tram)
      // retargets immediately; otherwise hold the eval cadence.
      if (lastSent?.key === followKey && nowMs < cameraEvalDueMsRef.current) return;
      const state = rt.engine.getState(followKey, nowMs);
      if (!state) {
        // The followed tram disappeared (left service / pruned) — end follow.
        selection.setFollowTramKey(null);
        lastSentCameraRef.current = null;
        return;
      }
      // Track where the tram is RENDERED. In live mode that is the PROJECTED
      // observation (the fix dead-reckoned to now) — anchoring to the raw fix
      // left the camera parked while the tram drove away.
      const isLive = positionMode === 'live';
      let anchor = state.position;
      let bearing = state.bearing;
      if (isLive) {
        const geometry = rt.engine.getGeometry(followKey);
        const projDist = state.projectedObservedDistM;
        if (geometry && projDist != null) {
          anchor = pointAt(geometry.coordinates, geometry.cumDistM, projDist);
          bearing = bearingAt(geometry.coordinates, geometry.cumDistM, projDist);
        } else {
          anchor = state.observedPosition;
          bearing = state.observedBearing;
        }
      }
      const overrides = gesture?.overrides ?? null;
      const target: FollowCameraTarget = {
        // Lead slightly toward where the tram will be at the next retarget.
        center: leadTarget(anchor, bearing, state.simSpeedKmh),
        zoom: overrides?.zoom ?? FOLLOW_ZOOM,
        pitch: overrides?.pitch ?? FOLLOW_PITCH,
        // Camera behind the tram, looking forward over the roof; the user's
        // rotation gesture persists as an offset from the tram bearing.
        heading: (((bearing + (overrides?.headingOffset ?? 0)) % 360) + 360) % 360,
      };
      // Deadband: visually identical to what the map is already showing —
      // skip the send (each one restarts a native animation). Movement, a
      // teleport, a gesture override change or the dwell ending all exceed
      // the deadband and send on the next eval; while parked, evals relax to
      // the dwell cadence.
      if (lastSent?.key === followKey && withinDeadband(lastSent, target)) {
        cameraEvalDueMsRef.current =
          nowMs +
          (state.simSpeedKmh < CAMERA_DWELL_SPEED_KMH ? CAMERA_DWELL_EVAL_MS : CAMERA_RETARGET_MS);
        return;
      }
      cameraEvalDueMsRef.current = nowMs + CAMERA_RETARGET_MS;
      lastSentCameraRef.current = { key: followKey, ...target };
      cameraRef.current?.setCamera({
        centerCoordinate: target.center,
        zoomLevel: target.zoom,
        pitch: target.pitch,
        heading: target.heading,
        animationMode: 'linearTo',
        animationDuration: CAMERA_GLIDE_MS,
      });
    });
  }, [cameraRef, viewportRef, followGestureRef]);

  // Tap ANY tram feature (badge/dot or any 3D body section): light haptic,
  // select + follow IMMEDIATELY, then open the sheet (its low detent keeps the
  // follow camera visible).
  const onPressTram = useCallback((event: { features: GeoJSON.Feature[] }) => {
    const key = event.features[0]?.properties?.key as string | undefined;
    if (!key) return;
    void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    const rt = getRuntime();
    const state = rt.engine.getState(key);
    if (state) rt.prioritizeTrip(state.snapshot.tripId);
    const selection = useSelectionStore.getState();
    selection.setSelectedTramKey(key);
    selection.setFollowTramKey(key);
    // Keys are usually registration numbers but can fall back to trip ids
    // containing URL-hostile characters — encode for the route param.
    router.push(`/tram/${encodeURIComponent(key)}`);
  }, []);

  // ShapeSource children must be a plain element array (no false/undefined
  // holes — rnmapbox clones each child to inject sourceID); the ModelLayer is
  // appended only once the GLBs are registered.
  const sectionLayers: ReactElement[] = [
    // Per-SECTION hit targets so a tap anywhere along a 30 m articulated body
    // (not just the head) opens/follows the tram. Active wherever the sections
    // source is fed.
    <CircleLayer
      key="tram-section-hit-targets"
      id="tram-section-hit-targets"
      slot="top"
      minZoomLevel={SECTIONS_FEED_MIN_ZOOM}
      style={{
        circleRadius: 22,
        circleColor: '#000000',
        circleOpacity: 0.011,
        circleStrokeWidth: 0,
      }}
    />,
  ];
  if (modelUris != null) {
    // Band 3–4 (≥14.8): articulated 3D sections. modelScale follows a clearly
    // cartoonish exponential curve: 5× at band entry (mid zoom = toy trams),
    // easing to real-world 1× only at z17. Oversized models overlapping at
    // hubs is acceptable per spec ("comically oversized").
    sectionLayers.push(
      <ModelLayer
        key="tram-models"
        id="tram-models"
        slot="top"
        minZoomLevel={BAND_BADGES_TO_MODELS - 0.05}
        style={{
          modelId: ['get', 'modelKey'],
          // SPIKE-VERIFIED orientation: trams authored front-toward −Z, so
          // z = bearing faces the model correctly (no heading offset).
          modelRotation: [0, 0, ['get', 'bearing']] as unknown as number[],
          modelScale: [
            'interpolate',
            ['exponential', 1.6],
            ['zoom'],
            BAND_BADGES_TO_MODELS,
            ['literal', [5, 5, 5]],
            15.6,
            ['literal', [3.2, 3.2, 3.2]],
            16.4,
            ['literal', [1.6, 1.6, 1.6]],
            MODEL_COMIC_REAL_SCALE_ZOOM,
            ['literal', [1, 1, 1]],
          ],
          modelOpacity: [
            'interpolate',
            ['linear'],
            ['zoom'],
            BAND_BADGES_TO_MODELS,
            0,
            BAND_BADGES_TO_MODELS + BAND_FADE,
            1,
          ],
          modelEmissiveStrength: 1.2,
          modelElevationReference: 'ground',
          // Shadows OFF (thermal): per-model shadow passes are the biggest GPU
          // cost at pitch; ambient occlusion stays on for grounding.
          modelCastShadows: false,
          modelReceiveShadows: false,
          modelType: 'common-3d',
        }}
      />,
    );
  }

  // Points-source children: plain element array, no false/undefined holes
  // (spike rule). The sprite-driven layers are appended only once <Images>
  // has the icons registered; until then a minimal fallback dot keeps the
  // fleet visible and tappable.
  const pointLayers: ReactElement[] = [
    // Gold halo under the selected tram, all zooms.
    <CircleLayer
      key="tram-selected-halo"
      id="tram-selected-halo"
      slot="top"
      filter={['==', ['get', 'selected'], 1]}
      style={{
        circleRadius: ['interpolate', ['linear'], ['zoom'], 12, 12, 16, 26],
        circleColor: Tram.gold,
        circleOpacity: 0.28,
        circleStrokeColor: Tram.gold,
        circleStrokeWidth: 2,
        circleStrokeOpacity: 0.9,
        circlePitchAlignment: 'map',
      }}
    />,
  ];
  if (iconImages != null) {
    pointLayers.push(
      // Band 1 (<13.2): direction teardrops — the whole marker rotates to the
      // tram bearing and lies flat on the map (Flightradar-style), so heading
      // is readable at city scale.
      <SymbolLayer
        key="tram-dots"
        id="tram-dots"
        slot="top"
        maxZoomLevel={BAND_DOTS_TO_BADGES + BAND_FADE}
        style={{
          iconImage: DOT_ICON,
          iconRotate: ['get', 'bearing'],
          iconRotationAlignment: 'map',
          iconPitchAlignment: 'map',
          iconAllowOverlap: true,
          iconIgnorePlacement: true,
          iconSize: ['interpolate', ['linear'], ['zoom'], 10, 0.55, BAND_DOTS_TO_BADGES, 0.8],
          iconOpacity: [
            'interpolate',
            ['linear'],
            ['zoom'],
            BAND_DOTS_TO_BADGES - BAND_FADE,
            1,
            BAND_DOTS_TO_BADGES + BAND_FADE,
            0,
          ],
        }}
      />,
      // Band 2 (13.2–14.8): the tram MARKER — a map-aligned teardrop at the
      // true position, rotated to the bearing (direction stays readable while
      // the capsule label floats above it, FR24-style).
      <SymbolLayer
        key="tram-badge-markers"
        id="tram-badge-markers"
        slot="top"
        minZoomLevel={BAND_DOTS_TO_BADGES - BAND_FADE}
        maxZoomLevel={BAND_BADGES_TO_MODELS + BAND_FADE + 0.1}
        style={{
          iconImage: DOT_ICON,
          iconRotate: ['get', 'bearing'],
          iconRotationAlignment: 'map',
          iconPitchAlignment: 'map',
          iconAllowOverlap: true,
          iconIgnorePlacement: true,
          iconSize: 0.6,
          iconOpacity: BADGE_BAND_OPACITY,
        }}
      />,
      // Band 2: model capsule label floating just above the marker — side
      // silhouette baked into the sprite, live line number seated in the
      // darkened left zone. iconOffset/textOffset scale in lockstep with
      // iconSize/textSize, so the label stays glued across the band.
      <SymbolLayer
        key="tram-badges"
        id="tram-badges"
        slot="top"
        minZoomLevel={BAND_DOTS_TO_BADGES - BAND_FADE}
        maxZoomLevel={BAND_BADGES_TO_MODELS + BAND_FADE + 0.1}
        style={{
          iconImage: CAP_ICON,
          iconAnchor: 'bottom',
          iconOffset: [0, -14],
          iconAllowOverlap: true,
          iconIgnorePlacement: true,
          iconSize: ['interpolate', ['linear'], ['zoom'], 13.2, 0.7, 14.8, 1],
          iconOpacity: BADGE_BAND_OPACITY,
          textField: ['get', 'line'],
          textFont: ['DIN Pro Bold', 'Arial Unicode MS Regular'],
          textSize: [
            'interpolate',
            ['linear'],
            ['zoom'],
            13.2,
            0.7 * CAP_TEXT_MAX_SIZE,
            14.8,
            CAP_TEXT_MAX_SIZE,
          ],
          textColor: '#FFFFFF',
          textOffset: [CAP_TEXT_OFFSET_EM, CAP_TEXT_OFFSET_UP_EM],
          textAllowOverlap: true,
          textIgnorePlacement: true,
          textOpacity: BADGE_BAND_OPACITY,
        }}
      />,
      // Band 2: gold star pinned to favorite trams' capsules.
      <SymbolLayer
        key="tram-badge-fav"
        id="tram-badge-fav"
        slot="top"
        filter={['==', ['get', 'favorite'], 1]}
        minZoomLevel={BAND_DOTS_TO_BADGES - BAND_FADE}
        maxZoomLevel={BAND_BADGES_TO_MODELS + BAND_FADE + 0.1}
        style={{
          iconImage: 'fav-star',
          iconAllowOverlap: true,
          iconIgnorePlacement: true,
          iconSize: 0.65,
          iconOffset: [48, -50],
          iconOpacity: BADGE_BAND_OPACITY,
        }}
      />,
    );
  } else {
    // Sprites still resolving (or failed): minimal legacy dot keeps every
    // tram visible + tappable across bands 1–2.
    pointLayers.push(
      <CircleLayer
        key="tram-dots-fallback"
        id="tram-dots-fallback"
        slot="top"
        maxZoomLevel={BAND_BADGES_TO_MODELS + BAND_FADE + 0.1}
        style={{
          circleRadius: ['interpolate', ['linear'], ['zoom'], 10, 3, 14.8, 6],
          circleColor: ['case', NIGHT_LINE, Tram.night, Tram.pidRed],
          circleStrokeWidth: 1.5,
          circleStrokeColor: '#FFFFFF',
        }}
      />,
    );
  }
  pointLayers.push(
    // Transparent hit-test target across ALL zooms (ModelLayer taps are
    // unreliable — spike convention). Near-zero opacity keeps it rendered
    // so native hit-testing still sees the features.
    <CircleLayer
      key="tram-hit-targets"
      id="tram-hit-targets"
      slot="top"
      style={{
        circleRadius: 26,
        circleColor: '#000000',
        circleOpacity: 0.011,
        circleStrokeWidth: 0,
      }}
    />,
  );

  return (
    <>
      {modelUris != null && <Models models={modelUris} />}
      {iconImages != null && <Images images={iconImages} />}

      <ShapeSource id="trams-points" ref={pointsRef} shape={EMPTY_FC} onPress={onPressTram}>
        {pointLayers}
      </ShapeSource>

      <ShapeSource id="trams-sections" ref={sectionsRef} shape={EMPTY_FC} onPress={onPressTram}>
        {sectionLayers}
      </ShapeSource>

      {/* Last-real-fix overlay for the selected/followed tram: dashed gold
          connector from the rendered position to the raw AVL fix + a small
          white/gold fix dot. Fed imperatively at the sections cadence; the FC
          is empty for everything but the selected tram. */}
      <ShapeSource id="tram-fix-overlay" ref={fixOverlayRef} shape={EMPTY_FC}>
        <LineLayer
          id="tram-fix-connector"
          slot="top"
          style={{
            lineColor: Tram.gold,
            lineWidth: 2,
            lineOpacity: 0.9,
            lineDasharray: [1.5, 1.5],
            lineCap: 'round',
          }}
        />
        <CircleLayer
          id="tram-fix-dot"
          slot="top"
          filter={['==', ['geometry-type'], 'Point']}
          style={{
            circleRadius: ['interpolate', ['linear'], ['zoom'], 13, 3, 17, 4.5],
            circleColor: '#FFFFFF',
            circleStrokeColor: Tram.gold,
            circleStrokeWidth: 2,
            circleOpacity: 0.95,
            circleStrokeOpacity: 0.95,
            circlePitchAlignment: 'map',
          }}
        />
      </ShapeSource>
    </>
  );
}
